"""Façana de compatibilitat per al backend afegir entorns.

La implementació es divideix en mòduls centrats, però aquest fitxer manté el fitxer
públic API utilitzat per la pàgina estable Streamlit.
"""

from __future__ import annotations

from backend.afegir_entorn_analysis import (
    ProbeReward,
    build_actuator_label,
    build_training_analysis,
    default_bounds_for_category,
    extract_schedule_numeric_values,
    extract_schedule_type_index,
    extract_schedule_value_range,
    extract_scheduled_hvac_controller_candidates,
    extract_storage_controller_candidates,
    extract_thermostat_schedule_candidates,
    find_available_meter,
    find_available_output_variable,
    load_building_json,
    parse_available_handlers,
    probe_available_handlers,
    resolve_schedule_name,
    summarize_references,
)
from backend.afegir_entorn_config import (
    add_variable_spec,
    build_action_space_expression,
    build_environment_config,
    build_registered_env_id,
    build_training_observation_config,
    build_variable_name_for_actuator,
    build_variable_output_names,
    cleanup_failed_environment,
    register_environment_from_yaml,
    validate_registered_environment,
    write_yaml_config,
)
from backend.afegir_entorn_common import (
    DEFAULT_TIME_VARIABLES,
    DEFAULT_WEATHER_VARIABILITY,
    DETAILED_HVAC_METER_CANDIDATES,
    ENERGY_METER_CANDIDATES,
    ENERGY_VARIABLE_CANDIDATES,
    ENERGYPLUS_SUBPROCESS_TIMEOUT_SECONDS,
    ENV_VALIDATION_TIMEOUT_SECONDS,
    FALLBACK_UPDATER_DIR,
    STANDARD_WEATHER_VARIABLES,
    STANDARD_ZONE_VARIABLES,
    TARGET_EPLUS_VERSION,
    TRANSITION_DOWNLOAD_URL,
)
from backend.afegir_entorn_conversion import (
    convert_idf_to_epjson,
    detect_idf_version,
    download_transition_tools,
    get_transition_updater_dir,
    needs_idf_upgrade,
    upgrade_idf_version,
)
from backend.afegir_entorn_common import (
    ActuatorOption,
    BuildingTrainingAnalysis,
    EnvironmentValidationResult,
    UpgradeResult,
)
from backend.afegir_entorn_common import (
    normalize_token,
    sanitize_identifier,
    save_uploaded_bytes,
    unique_identifier,
)
from backend.common import BUILDINGS_DIR, CFG_DIR, PKG_DIR, WEATHERS_DIR
from backend.weather_profiles import (
    WeatherProfileSuggestion,
    build_weather_profile_suggestions,
    build_weather_temperature_preview,
    build_weather_temperature_preview_figure,
    load_epw_dry_bulb_series,
    summarize_weather_file,
)

CFG_DIR.mkdir(parents=True, exist_ok=True)

__all__ = [
    "ActuatorOption",
    "BUILDINGS_DIR",
    "BuildingTrainingAnalysis",
    "CFG_DIR",
    "DEFAULT_TIME_VARIABLES",
    "DEFAULT_WEATHER_VARIABILITY",
    "DETAILED_HVAC_METER_CANDIDATES",
    "ENERGYPLUS_SUBPROCESS_TIMEOUT_SECONDS",
    "ENERGY_METER_CANDIDATES",
    "ENERGY_VARIABLE_CANDIDATES",
    "ENV_VALIDATION_TIMEOUT_SECONDS",
    "EnvironmentValidationResult",
    "FALLBACK_UPDATER_DIR",
    "PKG_DIR",
    "ProbeReward",
    "STANDARD_WEATHER_VARIABLES",
    "STANDARD_ZONE_VARIABLES",
    "TARGET_EPLUS_VERSION",
    "TRANSITION_DOWNLOAD_URL",
    "UpgradeResult",
    "WEATHERS_DIR",
    "WeatherProfileSuggestion",
    "add_variable_spec",
    "build_action_space_expression",
    "build_actuator_label",
    "build_environment_config",
    "build_registered_env_id",
    "build_training_analysis",
    "build_training_observation_config",
    "build_variable_name_for_actuator",
    "build_variable_output_names",
    "build_weather_profile_suggestions",
    "build_weather_temperature_preview",
    "build_weather_temperature_preview_figure",
    "cleanup_failed_environment",
    "convert_idf_to_epjson",
    "default_bounds_for_category",
    "detect_idf_version",
    "download_transition_tools",
    "extract_schedule_numeric_values",
    "extract_schedule_type_index",
    "extract_schedule_value_range",
    "extract_scheduled_hvac_controller_candidates",
    "extract_storage_controller_candidates",
    "extract_thermostat_schedule_candidates",
    "find_available_meter",
    "find_available_output_variable",
    "get_transition_updater_dir",
    "load_building_json",
    "load_epw_dry_bulb_series",
    "needs_idf_upgrade",
    "normalize_token",
    "parse_available_handlers",
    "probe_available_handlers",
    "register_environment_from_yaml",
    "resolve_schedule_name",
    "sanitize_identifier",
    "save_uploaded_bytes",
    "summarize_references",
    "summarize_weather_file",
    "unique_identifier",
    "upgrade_idf_version",
    "validate_registered_environment",
    "write_yaml_config",
]
